title: "Operation Endgame — TryHackMe"
description: "Professional Active Directory penetration testing documentation for the Operation Endgame room."
theme: jekyll-theme-primer

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - docs
